/* Auto-generated by scripts/texture_prep/gen_palette_firmware_headers.py */
/* 与 assets/generated/palette_default.json 及 scripts/common/palette_defaults.py 一致 */
#ifndef PALETTE_DEFAULTS_H
#define PALETTE_DEFAULTS_H
#include <stdint.h>
#include <avr/pgmspace.h>

#define PALETTE_NUM_INDICES 84u

/* 上电/编译须与《游戏内 9 快选=约定默认格》一致, 与 DRAW_QUICK_INDEX_INIT/槽序绑定 */
static const uint8_t PALETTE_DEFAULT_NINE[9] PROGMEM = { 72u, 0u, 46u, 45u, 44u, 42u, 41u, 39u, 37u };

#endif
