#!/usr/bin/env python3
"""从 palette JSON 生成固件用 palette_defaults.h 与 palette_index_rc.h（与 common/palette_defaults.py 同源）。"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_SCR = Path(__file__).resolve().parent
if str(_SCR) not in sys.path:
    sys.path.insert(0, str(_SCR))
if str(_SCR.parent) not in sys.path:
    sys.path.insert(0, str(_SCR.parent))

from common.palette_defaults import default_nine_indices_from_palette_path

_REPO = Path(__file__).resolve().parent.parent.parent


def _index_tables_from_json(path: Path) -> tuple[list[int], list[int]]:
    import json

    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    rows: list[int] = [0] * 84
    cols: list[int] = [0] * 84
    for c in data["colors"]:
        idx = int(c["index"])
        if not 0 <= idx <= 83:
            raise ValueError(f"bad index {idx}")
        rows[idx] = int(c["row"])
        cols[idx] = int(c["col"])
    return rows, cols


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--palette-json",
        type=Path,
        default=_REPO / "assets" / "generated" / "palette_default.json",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=_REPO / "firmware" / "paint_vector_flash",
    )
    args = ap.parse_args()
    p = args.palette_json
    outd = args.out_dir
    outd.mkdir(parents=True, exist_ok=True)

    nine = default_nine_indices_from_palette_path(p)
    rows, cols = _index_tables_from_json(p)

    def_h = outd / "palette_defaults.h"
    rc_h = outd / "palette_index_rc.h"

    def_h.write_text(
        "\n".join(
            [
                "/* Auto-generated by scripts/texture_prep/gen_palette_firmware_headers.py */",
                "/* 与 assets/generated/palette_default.json 及 scripts/common/palette_defaults.py 一致 */",
                "#ifndef PALETTE_DEFAULTS_H",
                "#define PALETTE_DEFAULTS_H",
                "#include <stdint.h>",
                "#include <avr/pgmspace.h>",
                "",
                f"#define PALETTE_NUM_INDICES 84u",
                "",
                "/* 上电/编译须与《游戏内 9 快选=约定默认格》一致, 与 DRAW_QUICK_INDEX_INIT/槽序绑定 */",
                f"static const uint8_t PALETTE_DEFAULT_NINE[9] PROGMEM = {{ {', '.join(f'{n}u' for n in nine)} }};",
                "",
                "#endif",
                "",
            ]
        ),
        encoding="utf-8",
    )

    rc_h.write_text(
        "\n".join(
            [
                "/* Auto-generated — index 0..83 → 全色 12×7 格 (0-based row, col) */",
                "#ifndef PALETTE_INDEX_RC_H",
                "#define PALETTE_INDEX_RC_H",
                "#include <stdint.h>",
                "#include <avr/pgmspace.h>",
                "",
                f"static const uint8_t PAL_INDEX_ROW[84] PROGMEM = {{ {', '.join(f'{r}u' for r in rows)} }};",
                f"static const uint8_t PAL_INDEX_COL[84] PROGMEM = {{ {', '.join(f'{c}u' for c in cols)} }};",
                "",
                "#endif",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(f"Wrote {def_h}")
    print(f"Wrote {rc_h}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
